name: Docker Build and Run Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build -t debug-test-image .

    - name: Run Docker Container
      run: docker run --rm debug-test-image /bin/sh -c "echo 'Container is running successfully'"

    - name: Verify pre-installed tools
      run: docker run --rm debug-test-image /bin/sh -c "command -v gdb && command -v objdump && command -v echo && echo 'All tools are available!'"

    - name: Cleanup
      run: docker system prune -af
